### ISSUE TITLE
Loading ding on a server will cause the entire server to crash / not launch.

### ISSUE THREAD

**Issue by Joshument** [Draylar/ding#9]
Full log here: https://pastebin.com/SvJF0njr

Lines that might be concerning:
Caused by: net.minecraftforge.fml.ModLoadingException: Ding has class loading errors
?7java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:67) ~[forge:34.1] {re:classloading}
        at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source) ~[?:?] {}
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261] {}
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261] {}
        at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[forge:34.1] {re:classloading}
        ... 35 more

(I can't expand the ...35 more as it was run using a java command in cmd prompt, sorry.)

**Comment by Draylar** [comment]
I think you might be looking for [Ding by iChun](https://github.com/iChun/Ding). This repo is for a Fabric alternative to that mod.
